name: 'Set and export environment variable'
description: 'Set and export environment variable to be available for the steps that follow.'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  name:
    description: 'name of the variable'
    required: true
  value:
    description: 'value of the variable'
    required: true
runs:
  using: "composite"
  steps:
    - name: export environment variable
      run: echo "${{ inputs.name }}=${{ inputs.value }}" >> $GITHUB_ENV
